ares:
  generator:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ares?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root1234
    databaseName: ares
    tableName: test_v
    tablePrefix: t_
    generatorLevel: 3
    basePackage: com.ares.system
    entityPackage: com.ares.system.persistence.model
    daoPackage: com.ares.system.persistence.dao
    xmlDir: .src.main.resources.mapping
    servicePackage: com.ares.system.persistence.service
    controllerPackage: com.ares.system.controller
    templatePath: /ares-generator/src/main/resources/templates
