#基本配置信息
ares:
  base:
    name: ARES
    version: V1.0.0
    copyright: Copyright © 2020-2030 ${ares.base.name}-${ares.base.version}
    #全局session时间
    timeout: 3600
  #swagger配置
  swagger:
    enable: true
    base:
      package: com.ares
    contact:
      email: ares@ares.com
      name: ares
      url: www.ares.com
    description: ${ares.base.name} API 接口文档
    title: ${ares.base.name} API Documents
    url: ares
    version: ${ares.base.version}
    parameter-config:
      - name: Authorization
        description: Token Request Header
        type: header
        data-type: String
        required: false
        default-value:
