#基本配置信息
ares:
  base:
    name: ARES
    version: V6.0.2
    copyright: Copyright © 2020-2030 ${ares.base.name}-${ares.base.version}
    #全局session时间
    timeout: 3600
  #swagger配置
  swagger:
    enable: true
    base:
      package: com.ares
    contact:
      email: ares@ares.com
      name: ares
      url: www.ares.com
    description: ${ares.base.name} API 接口文档
    title: ${ares.base.name} API Documents
    url: ares
    version: ${ares.base.version}
    parameter-config:
      - name: Authorization
        description: Token Request Header
        type: header
        data-type: String
        required: false
        default-value:

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: ares-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: ${ares.base.timeout}
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: ${ares.base.timeout}
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  is-read-header: true
  is-write-header: true
  is-print: false
