server:
  servlet:
    context-path: /ares
  port: 8080
  undertow:
    url-charset: UTF-8
    threads:
      worker: 10
      io: 10
spring:
  profiles:
    active: @profileActive@
    include: ares,quartz,message,neo4j,generator,flowable
  application:
    name: Ares
  devtools:
    restart:
      enabled: false
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
        instance:
          name: ${spring.application.name}
          service-base-url: http://localhost:${server.port}
        monitor:
          period: 100000
          status-lifetime: 100000
          connect-timeout: 100000
          read-timeout: 100000

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  type-aliases-package: com.ares.**.**.model
  config-location: classpath:mybatis-config.xml

#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
path:
  log: logs

management:
  health:
    neo4j:
      enabled: false
    rabbit:
      enabled: false
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


info:
  project-name: ${spring.application.name}
  project-groupId: '@project.parent.groupId@'
  project-author: Young
  project-description: ${spring.application.name} project
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-version: '@project.version@'

jeecg:
  jmreport:
    # 自动保存
    autoSave: true
    # 单位毫秒 默认5*60*1000
    interval: 10000
    #多租户模式，默认值为空(created:按照创建人隔离、tenant:按照租户隔离) (v1.6.2+ 新增)
#    saasMode: created
    # 平台上线安全配置(v1.6.2+ 新增)
    firewall:
      # 数据源安全 (开启后，不允许使用平台数据源、SQL解析加签并不允许查询数据库)
      dataSourceSafe: false
      # 低代码开发模式（dev:开发模式，prod:发布模式—关闭在线报表设计功能，分配角色admin、lowdeveloper可放开限制）
      lowCodeMode: dev
