spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://10.211.55.4:3306/ares?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: ENC(QHRpFBBFEiZnp0in9N+XBa5nSwJr6NLnegTQHmCYbAYW0ox/Uyb84OcsXcAMMZ2IBEbyCmAdwKLJL8wnxVLRBA==)
          public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIrH/MhPNd8nH3mxpEMSOtj554RmecKDfaOsJa/6+yMBRcFf0bva3npJIm7qNnR5lNFU7kPxENJN95DoPUl032UCAwEAAQ==
        slave:
          url: jdbc:mysql://localhost:3306/ares?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: ENC(QHRpFBBFEiZnp0in9N+XBa5nSwJr6NLnegTQHmCYbAYW0ox/Uyb84OcsXcAMMZ2IBEbyCmAdwKLJL8wnxVLRBA==)
          public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIrH/MhPNd8nH3mxpEMSOtj554RmecKDfaOsJa/6+yMBRcFf0bva3npJIm7qNnR5lNFU7kPxENJN95DoPUl032UCAwEAAQ==
      hikari:
        max-lifetime: 1800000
        connection-timeout: 5000
        idle-timeout: 3600000
        max-pool-size: 12
        min-idle: 4
        connection-test-query: select 1

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
