server:
  servlet:
    context-path: /ares
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30
spring:
  profiles:
    include: @profileActive@,ares,quartz,message,activiti,neo4j
  application:
    name: Ares
  devtools:
    restart:
      enabled: false
  mvc:
    static-path-pattern: /static/**
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
        instance:
          name: ${spring.application.name}
          service-base-url: http://localhost:${server.port}
        monitor:
          period: 100000
          status-lifetime: 100000
          connect-timeout: 100000
          read-timeout: 100000
mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  type-aliases-package: com.ares.**.**.model
  config-location: classpath:mybatis-config.xml

#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/${spring.application.name}.log
path:
  log: logs

management:
  health:
    neo4j:
      enabled: false
    rabbit:
      enabled: false
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


info:
  project-name: ${spring.application.name}
  project-groupId: '@project.parent.groupId@'
  project-author: Young
  project-description: ${spring.application.name} project
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-version: '@project.version@'

